let carouselImagesSrc = [
  "GameScreenshot_1.png",
  "GameScreenshot_29.png",
  "GameScreenshot_14.png",
  "GameScreenshot_19.png",
  "GameScreenshot_28.png",
  "GameScreenshot_7.png",
  "GameScreenshot_21.png",
  "GameScreenshot_4.png",
  "GameScreenshot_26.png",
  "GameScreenshot_25.png",
  "GameScreenshot_6.png",
  "GameScreenshot_24.png",
  "GameScreenshot_15.png",
  "GameScreenshot_23.png",
  "GameScreenshot_8.png",
  "GameScreenshot_22.png",
  "GameScreenshot_9.png",
  "GameScreenshot_10.png",
  "GameScreenshot_21.png",
  "GameScreenshot_11.png",
  "GameScreenshot_12.png",
  "GameScreenshot_13.png",
  "GameScreenshot_18.png",
  "GameScreenshot_17.png",
];
export default carouselImagesSrc;
