export default {
  carouselPictures: [
    "GameScreenshot_1.png",
    "GameScreenshot_29.png",
    "GameScreenshot_14.png",
    "GameScreenshot_19.png",
    "GameScreenshot_28.png",
    "GameScreenshot_7.png",
    "GameScreenshot_21.png",
    "GameScreenshot_4.png",
    "GameScreenshot_26.png",
    "GameScreenshot_25.png",
    "GameScreenshot_6.png",
    "GameScreenshot_24.png",
    "GameScreenshot_15.png",
    "GameScreenshot_23.png",
    "GameScreenshot_8.png",
    "GameScreenshot_22.png",
    "GameScreenshot_9.png",
    "GameScreenshot_10.png",
    "GameScreenshot_21.png",
    "GameScreenshot_11.png",
    "GameScreenshot_12.png",
    "GameScreenshot_13.png",
    "GameScreenshot_18.png",
    "GameScreenshot_17.png",
  ],
  gameCards: [
    {
      availability: "Available now!",
      title: "Doge",
      text: "The great and epic Doge game! Our first game ever. Made in just 2 weeks! Take control of lost doge trying to find his way out of town. Be careful! You will encounter many dogcatchers along the way. Also, those bones look really delicious.",
      imageSrc: "cards/doge1.png",
      gameName: "doge",
    },

    {
      availability: "Available in July!",
      title: "Stranded Away",
      text: "2D shooter/puzzle game about exploring abandoned planets. You are playing a hero whose job is to save the galaxy from evil scientist Dr. Hone. Game is currently still work in progress!",
      imageSrc: "cards/stranded1.png",
      gameName: "stranded-away",
    },
  ],
  news: [
    {
      icon: "mdi-newspaper-variant",
      date: "3 July, 2021",
      title: "MacroQuiet is born!",
      text: "Bring in the Champagne!",
    },
    {
      icon: "mdi-newspaper-variant",
      date: "21 July, 2021",
      title: "Doge game available now!",
      text: "The great and epic Doge game! Our first game ever. Made in just 2 weeks! Take control of lost doge trying to find his way out of town. Be careful! You will encounter many dogcatchers along the way. Also, those bones look really delicious.",
    },
    {
      icon: "mdi-newspaper-variant",
      date: "28 May, 2022",
      title: "Stranded Away coming soon!",
      text: "2D shooter/puzzle game about exploring abandoned planets. You are playing a hero whose job is to save the galaxy from evil scientist Dr. Hone. Game is currently still in progress!",
    },
  ],
};
